spring.application.name=random-user-api

randomuser.base-url=https://randomuser.me

#timeouts sec
randomuser.connect-timeout=2
randomuser.read-timeout=3


#CORS
cors.allowed-origins=http://localhost:8080
